# Default values for sbombastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/controller
    tag: v0.0.1
    pullPolicy: IfNotPresent
  replicas: 3
  logLevel: "info"

storage:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/storage
    tag: v0.0.1
    pullPolicy: IfNotPresent
  replicas: 1
  # logLevel: "debug" //TODO: uncomment this, when the log parser in storage is implemented

worker:
  image:
    repository: ghcr.io/rancher-sandbox/sbombastic/worker
    tag: v0.1.0-alpha1
    pullPolicy: IfNotPresent
  replicas: 3
  logLevel: "info"

persistence:
  enabled: true

  ## Specify a PVC for the storage data
  storageData:
    enabled: true
    subPath: null
    annotations: {}
    labels: {}
    # storageClass: ""
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    accessMode: ReadWriteOnce
    size: 1Gi

# NOTE: This section is used to configure the NATS server and its components
# deployed by the NATS chart dependency.
# Do not edit this section manually.
nats:
  tlsCA:
    enabled: true
    secretName: sbombastic-nats-server-tls
  config:
    nats:
      tls:
        enabled: true
        secretName: sbombastic-nats-server-tls
        merge:
          verify: true
    cluster:
      enabled: true
      tls:
        enabled: true
        secretName: sbombastic-nats-routes-tls
    jetstream:
      enabled: true
  natsBox:
    enabled: false
  container:
    merge:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
            type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
            drop:
            - "ALL"
  reloader:
    merge:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
            type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
            drop:
            - "ALL"
