apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" .| nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{ include "sbombastic.selectorLabels" .| nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" .| nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "sbombastic.fullname" . }}-worker
      containers:
        - name: worker
          image: '{{ template "system_default_registry" . }}{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}'
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{ include "sbombastic.securityContext" . | nindent 12 }}
          args:
            - -nats-url
            - {{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222
            {{- if .Values.worker.logLevel }}
            - -log-level={{ .Values.worker.logLevel }}
            {{- end }}
          volumeMounts:
            - mountPath: /var/run/worker
              name: run-volume
            - mountPath: /tmp
              name: tmp-dir
            - mountPath: "/nats/tls"
              name: nats-tls
              readOnly: true
      volumes:
        - name: run-volume
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}
        - name: nats-tls
          secret:
            secretName: {{ include "sbombastic.fullname" . }}-nats-worker-client-tls
