---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sbombastic-cnpg-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sbombastic-cnpg-server-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: sbombastic-selfsigned-cnpg-server-ca
  secretName: sbombastic-cnpg-server-ca-key-pair
  duration: 8736h
  renewBefore: 240h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sbombastic-cnpg-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sbombastic-cnpg-server-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: sbombastic-cnpg-server-ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: sbombastic-cnpg-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sbombastic-cnpg-server-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: sbombastic-cnpg-server-cert
  usages:
    - server auth
  dnsNames:
    - sbombastic-cnpg-cluster-rw
    - sbombastic-cnpg-cluster-rw.{{ .Release.Namespace }}
    - sbombastic-cnpg-cluster-rw.{{ .Release.Namespace }}.svc
    - sbombastic-cnpg-cluster-rw.{{ .Release.Namespace }}.svc.cluster.local
    - sbombastic-cnpg-cluster-r
    - sbombastic-cnpg-cluster-r.{{ .Release.Namespace }}
    - sbombastic-cnpg-cluster-r.{{ .Release.Namespace }}.svc
    - sbombastic-cnpg-cluster-r.{{ .Release.Namespace }}.svc.cluster.local
    - sbombastic-cnpg-cluster-ro
    - sbombastic-cnpg-cluster-ro.{{ .Release.Namespace }}
    - sbombastic-cnpg-cluster-ro.{{ .Release.Namespace }}.svc
    - sbombastic-cnpg-cluster-ro.{{ .Release.Namespace }}.svc.cluster.local
  duration: 2160h
  renewBefore: 240h
  issuerRef:
    name: sbombastic-cnpg-server-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sbombastic-cnpg-client-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: sbombastic-selfsigned-cnpg-client-ca
  secretName: sbombastic-cnpg-client-ca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 8736h
  renewBefore: 240h
  issuerRef:
    name: sbombastic-cnpg-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sbombastic-cnpg-client-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: sbombastic-cnpg-client-ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: sbombastic-cnpg-client-cert
  namespace: {{ .Release.Namespace }}
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sbombastic-cnpg-client-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: sbombastic-cnpg-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  duration: 2160h
  renewBefore: 240h
  issuerRef:
    name: sbombastic-cnpg-client-issuer
    kind: Issuer
    group: cert-manager.io
