apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      {{ include "sbombastic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" . | nindent 8 }}
        app.kubernetes.io/component: storage
    spec:
      serviceAccountName: {{ include "sbombastic.fullname" . }}-storage
      containers:
        - name: storage
          image: {{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag }}
          securityContext:
            {{ include "sbombastic.securityContext" . | nindent 12 }}
          args:
            - --cert-dir=/certs
          {{- if .Values.storage.logLevel }}
            - -log-level={{ .Values.storage.logLevel }}
          {{- end }}
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
          volumeMounts:
            - name: sqlite-pvc
              mountPath: /data/sqlite/
            - name: cert-volume
              mountPath: /certs
            - name: client-ca-key-pair-volume
              mountPath: /certs/client-ca-key-pair
            - name: server-ca-volume
              mountPath: /certs/server-ca
            - name: cnpg-cluster-password-volume
              mountPath: /certs/cnpg-cluster-password
      volumes:
        - name: sqlite-pvc
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.storageData.existingClaim }}{{ .Values.persistence.storageData.existingClaim }}{{- else }}{{ template "sbombastic.fullname" . }}-storage-data{{- end }}
        - name: cert-volume
          emptyDir: {}
        - name: client-ca-key-pair-volume
          secret:
            secretName: {{ if .Values.storage.cnpg.createCluster }}{{ .Values.storage.cnpg.secret.clientCAKeyPair }}{{- else }}{{ template "sbombastic.fullname" . }}-cnpg-client-ca-key-pair{{- end }}
            defaultMode: 0400
        - name: server-ca-volume
          secret:
            secretName: {{ if .Values.storage.cnpg.createCluster }}{{ .Values.storage.cnpg.secret.serverCA }}{{- else }}{{ .Values.cluster.cluster.certificates.serverCASecret }}{{- end }}
            defaultMode: 0400
        - name: cnpg-cluster-password-volume
          secret:
            secretName: {{ if .Values.storage.cnpg.createCluster }}{{ .Values.storage.cnpg.secret.password }}{{- else }}{{ .Values.cluster.fullnameOverride }}-app{{- end }}
            defaultMode: 0400
