name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  detect-chart-update:
    runs-on: ubuntu-latest
    outputs:
      version_bumped: ${{ steps.check_ver.outputs.bumped }}
    steps:
      - name: Checkout with history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@307ce72e224b82157cc31c78828f168b8e55d47d # v2.84.0
      - name: Check Chart version bump
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check_ver
        run: |
          set -e
          changed=$(updatecli diff --config updatecli/updatecli.d/helm-chart-update-detect.yaml --values updatecli/values.yaml)
          echo "changed: $changed"

          # Goal is to get the number of changed pipelines
          # Run Summary
          # ===========
          # Pipeline(s) run:
          #   * Changed:	1
          #   * Failed:	0
          #   * Skipped:	0
          #   * Succeeded:	0
          #   * Total:	1
          summary=$(echo "$changed" | sed -n '/Pipeline(s) run:/,/^$/p')
          echo "summary: $summary"

          changed=$(echo "$summary" | grep 'Changed:' | sed -E 's/.*Changed:[[:space:]]*([0-9]+).*/\1/')
          echo "changed: $changed"

          if [ "$changed" -ne 0 ]; then
          echo "version_bumped=true"
          else
          echo "version_bumped=false"
          fi
  bump-chart-version:
    needs: [detect-chart-update]
    if: needs.detect-chart-update.outputs.version_bumped == 'true'
    uses: ./.github/workflows/update-charts.yml
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    secrets: inherit

  release-chart:
    needs: [detect-chart-update]
    permissions:
      contents: write # chart-releaser needs to release the charts to the repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Add dependency chart repos
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"