# .github/workflows/label-merged-pr.yml
name: Label Merged PR on Push

on:
  workflow_call:

  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  contents: read          # you don’t need to write files
  issues: write    # to write labels on PRs

jobs:
  label-merged-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Find and label merged PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              commit_sha: context.sha
            });
            const pr = data.find(p => p.merged_at);
            if (!pr) core.setFailed(`No merged PR for ${context.sha}`);

            await github.rest.issues.addLabels({
              owner:        context.repo.owner,
              repo:         context.repo.repo,
              issue_number: pr.number,
              labels:       ['kind/feature']
            });
