name: Advanced PR Labeling

on:
  push:
    branches:
      - main
permissions:
  contents: write    # 创建 Release 需要
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create (or update) Draft Release with Auto-Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release create "$TAG" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Release $TAG" \
            --generate-notes \
            --draft