name: "Auto-Label by Branch (native)"

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents:      read    # 代码 checkout
  pull-requests: write   # 给 PR 打标签

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4        # 可选：如果你要读取仓库文件
      - uses: actions/labeler@v5
        with:
          repo-token:        ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels:       false      # 不会移除已存在但不再匹配的标签
          dot:               true       # 默认匹配以 “.” 开头的路径（无关分支）
