name: Advanced PR Labeling

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Label based on PR title (matching your autolabeler config)
      - name: Label based on title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const labels = [];

            // Tag any PR with "!" in the subject as breaking change
            if (title.includes('!:')) {
              labels.push('kind/breaking-change');
            }

            // Dependencies-related PRs
            if (title.includes('chore(deps)') || title.includes('fix(deps)') || title.includes('build(deps)')) {
              labels.push('area/dependencies');
            }

            // Feature PRs
            if (title.startsWith('feat')) {
              labels.push('kind/feature');
            }

            // Bug fix PRs
            if (title.startsWith('fix')) {
              labels.push('kind/bug');
            }

            // Chore PRs
            if (title.startsWith('chore')) {
              labels.push('kind/chore');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }