name: Release Please Create a Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write     # to create the Git tag & release
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          skip-github-pull-request: true
          skip-github-release: false
          config-file: .github/config/release-please/config.json
          manifest-file: .github/config/release-please/manifest.json
          draft: true
