name: Release Please Create a Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write     # to create the Git tag & release
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install release-please
        run: npm install --global release-please@v17.1.0
      - name: Create draft release
        run: |
          release-please github-release --token ${{ secrets.GITHUB_TOKEN }} --repo-url=${{ github.repository }} --config .github/config/release-please/config.json  --manifest-file .github/config/release-please/manifest.json
