name: Update helm charts
on:
  workflow_call:
  workflow_dispatch:
jobs:
  update-sbombastic-charts:
    name: Update SBOMbastic charts
    runs-on: ubuntu-latest
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@60a9429087baeeaa732fd853d44ae16a8334027e # v2.87.1

      - name: Update SBOMbastic charts
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli apply --config ./updatecli/updatecli.d/helm-chart-update.yaml --values updatecli/values.yaml"